name: CI

on:
  create:
    tags:
  push:
    paths-ignore:
      - '*/*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '*/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version: ['1.6', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]
      # fail-fast: true
    steps:
      - uses: actions/checkout@v1
#     - name: "Set up Julia"
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
#     - name: "Unit Test"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
#     - name: "Cover"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.version == '1.6' && matrix.os == 'ubuntu-latest' }}
        with:
          file: lcov.info
