name: CI

on:
  create:
    tags:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
      # jf: reduce testing for lower carbon footprint
      # version: ['1.4', '1', 'nightly']
        version: ['1.5', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]
      # fail-fast: true
    steps:
      - uses: actions/checkout@v1
#     - name: "Set up Julia"
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
#     - name: "Unit Test"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
#     - name: "Cover"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.version == '1.5' && matrix.os == 'ubuntu-latest' }}
        with:
          file: lcov.info
